shifts:
- startDate: Mon 29 Jun 2020
  user: ezimanyi
- startDate: Mon 06 Jul 2020
  user: jonsie
- startDate: Mon 13 Jul 2020
  user: mneterval@google.com
- startDate: Mon 20 Jul 2020
  user: plumpy@google.com
- startDate: Mon 27 Jul 2020
  user: robzienert
- startDate: Mon 03 Aug 2020
  user: ajordens
- startDate: Mon 10 Aug 2020
  user: cfieber
- startDate: Mon 17 Aug 2020
  user: ethanfrogers
- startDate: Mon 24 Aug 2020
  stopDate: Sun 30 Aug 2020
  user: ezimanyi
