shifts:
- startDate: Mon 11 May 2020
  user: jonsie
- startDate: Mon 18 May 2020
  user: mneterval@google.com
- startDate: Mon 25 May 2020
  user: plumpy@google.com
- startDate: Mon 01 Jun 2020
  user: robzienert
- startDate: Mon 08 Jun 2020
  user: ajordens
- startDate: Mon 15 Jun 2020
  user: cfieber
- startDate: Mon 22 Jun 2020
  user: ethanfrogers
- startDate: Mon 29 Jun 2020
  user: ezimanyi
- startDate: Mon 06 Jul 2020
  stopDate: Sun 12 Jul 2020
  user: jonsie
