shifts:
- startDate: Mon 30 Nov 2020
  user: cfieber
- startDate: Mon 07 Dec 2020
  user: claymccoy
- startDate: Mon 14 Dec 2020
  user: ethanfrogers
- startDate: Mon 21 Dec 2020
  user: mneterval@google.com
- startDate: Mon 28 Dec 2020
  user: jonsie
- startDate: Mon 04 Jan 2021
  user: mneterval@google.com
- startDate: Mon 11 Jan 2021
  user: plumpy@google.com
- startDate: Mon 18 Jan 2021
  stopDate: Sun 24 Jan 2021
  user: robzienert
