steps:
  - id: buildCompileImage
    waitFor: ["-"]
    name: gcr.io/cloud-builders/docker
    args: ["build", "-t", "compile", "-f", "Dockerfile.compile", "."]
  - id: buildSlimImage
    waitFor: ["buildCompileImage"]
    name: gcr.io/cloud-builders/docker
    args: ["build", "-t", "gcr.io/$PROJECT_ID/$_IMAGE_NAME:$TAG_NAME-slim", "-f", "Dockerfile.slim", "."]
  - id: buildUbuntuImage
    waitFor: ["buildCompileImage"]
    name: gcr.io/cloud-builders/docker
    args: ["build", "-t", "gcr.io/$PROJECT_ID/$_IMAGE_NAME:$TAG_NAME-ubuntu", "-f", "Dockerfile.ubuntu", "."]
  - id: tagDefaultImage
    waitFor: ["buildSlimImage"]
    name: gcr.io/cloud-builders/docker
    args: ["tag", "gcr.io/$PROJECT_ID/$_IMAGE_NAME:$TAG_NAME-slim", "gcr.io/$PROJECT_ID/$_IMAGE_NAME:$TAG_NAME"]
  - id: buildJava8Image
    waitFor: ["buildCompileImage"]
    name: gcr.io/cloud-builders/docker
    args: ["build", "-t", "gcr.io/$PROJECT_ID/$_IMAGE_NAME:$TAG_NAME-java8", "-f", "Dockerfile.java8", "."]
  - id: buildUbuntuJava8Image
    waitFor: ["buildCompileImage"]
    name: gcr.io/cloud-builders/docker
    args: ["build", "-t", "gcr.io/$PROJECT_ID/$_IMAGE_NAME:$TAG_NAME-ubuntu-java8", "-f", "Dockerfile.ubuntu-java8", "."]
images:
  - gcr.io/$PROJECT_ID/$_IMAGE_NAME:$TAG_NAME-slim
  - gcr.io/$PROJECT_ID/$_IMAGE_NAME:$TAG_NAME-ubuntu
  - gcr.io/$PROJECT_ID/$_IMAGE_NAME:$TAG_NAME
  - gcr.io/$PROJECT_ID/$_IMAGE_NAME:$TAG_NAME-java8
  - gcr.io/$PROJECT_ID/$_IMAGE_NAME:$TAG_NAME-ubuntu-java8
timeout: 3600s
options:
  machineType: N1_HIGHCPU_8
