server:
  port: 8087

aws:
  enabled: $AWS_ENABLED

docker:
  enabled: $DOCKER_ENABLED

google:
  enabled: $GOOGLE_ENABLED
  gce:
    bakeryDefaults:
      project: $GOOGLE_MANAGED_PROJECT_ID

rush:
  credentials: $GOOGLE_ACCOUNT_NAME
