server:
  port: 8080

aws:
  enabled: ${AWS_ENABLED:false}
  defaultSimpleDBDomain: CLOUD_REGISTRY

google:
  enabled: ${GOOGLE_ENABLED:false}

spinnaker:
  cassandra:
    enabled: false
    cluster: CASS_SPINNAKER
    keyspace: front50
    name: default
