server:
  port: 8084

services:
  oort:
    baseUrl: http://localhost/oort
  orca:
    baseUrl: http://localhost/orca
  front50:
    baseUrl: http://localhost/front50
  mort:
    baseUrl: http://localhost/mort
  kato:
    baseUrl: http://localhost/kato
#optional services:
  echo:
    enabled: false
  mayo:
    enabled: false
  flapjack:
    enabled: false
  igor:
    enabled: false
