version: "2"
services:
  clouddriver:
    env_file: ./compose.env
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
    image: quay.io/spinnaker/clouddriver:master
    ports:
      - "7002:7002"
  deck:
    environment:
      - "API_HOST=http://gate:8084"
      - DECK_HOST=0.0.0.0
      - DECK_PORT=9000
      - PROTOCOL=http
      - AUTH_ENABLED=true
      - "AUTH_ENDPOINT=http://gate:8084/auth/user"
    image: quay.io/spinnaker/deck:master
    ports:
      - "9000:9000"
  echo:
    env_file: ./compose.env
    environment:
      - "FRONT50_BASEURL=http://front50:8080"
      - "ORCA_BASEURL=http://orca:8083"
      - "JAVA_OPTS=-javaagent:/opt/echo/lib/jamm-0.2.5.jar"
    image: quay.io/spinnaker/echo:master
    ports:
      - "8089:8089"
  front50:
    env_file: ./compose.env
    environment:
      - "JAVA_OPTS=-javaagent:/opt/front50/lib/jamm-0.2.5.jar"
      - "AWS_ACCESS_KEY_ID=spindocker"
      - "AWS_SECRET_ACCESS_KEY=spindocker"
    image: quay.io/spinnaker/front50:master
    ports:
      - "8080:8080"
  gate:
    env_file: ./compose.env
    environment:
      - SERVICES_CLOUDDRIVER_HOST=clouddriver
      - SERVICES_ECHO_HOST=echo
      - SERVICES_FRONT50_HOST=front50
      - SERVICES_IGOR_HOST=igor
      - SERVICES_ORCA_HOST=orca
      - SERVICES_ROSCO_HOST=rosco
    image: quay.io/spinnaker/gate:master
    ports:
      - "8084:8084"
  igor:
    env_file: ./compose.env
    environment:
      - SERVICES_ECHO_HOST=echo
      - SERVICES_CLOUDDRIVER_HOST=clouddriver
    image: quay.io/spinnaker/igor:master
    ports:
      - "8088:8088"
  orca:
    env_file: ./compose.env
    environment:
      - SERVICES_CLOUDDRIVER_HOST=clouddriver
      - SERVICES_ECHO_HOST=echo
      - SERVICES_FRONT50_HOST=front50
      - SERVICES_IGOR_HOST=igor
      - SERVICES_ROSCO_HOST=rosco
    image: quay.io/spinnaker/orca:master
    ports:
      - "8083:8083"
  redis:
    command: "redis-server --appendonly yes"
    expose:
      - "6379"
    ports:
      - "6379:6379"
    image: redis
  rosco:
    env_file: ./compose.env
    image: quay.io/spinnaker/rosco:master
    ports:
      - "8087:8087"
  fiat:
    env_file: ./compose.env
    environment:
      - SERVICES_CLOUDDRIVER_BASEURL=clouddriver
      - SERVICES_FRONT50_BASEURL=front50
    image: quay.io/spinnaker/fiat:master
    ports:
      - "7003:7003"
  minio:
    command:
      - server
      - /opt/minio/storage
    env_file: ./compose.env
    image: minio/minio:latest
    ports:
      - "9001:9000"
    environment:
      - MINIO_ACCESS_KEY=spindocker
      - MINIO_SECRET_KEY=spindocker