clouddriver: 
  container_name: clouddriver
  env_file: ./compose.env
  image: spinnaker/clouddriver
  links: 
    - redis
  ports: 
    - "7002:7002"
  volumes: 
    - "../../config:/root/.spinnaker"
echo: 
  container_name: echo
  env_file: ./compose.env
  environment:
    - SERVICE_DEFAULT_HOST=$DOCKER_IP
  image: spinnaker/echo
  ports: 
    - "8089:8089"
  volumes: 
    - "../../config:/root/.spinnaker"
front50: 
  container_name: front50
  env_file: ./compose.env
  image: spinnaker/front50
  ports: 
    - "8080:8080"
  volumes: 
    - "../../config:/root/.spinnaker"
frontend: 
  container_name: deck
  image: spinnaker/deck
  ports: 
    - "9000:9000"
  environment:
    - API_HOST=$DOCKER_IP:8084
    - DECK_HOST=0.0.0.0
    - DECK_PORT=9000
    - PROTOCOL=http
gate: 
  container_name: gate
  env_file: ./compose.env
  environment:
    - SERVICE_DEFAULT_HOST=$DOCKER_IP
    - CLOUDDRIVER_BASE_URL=$DOCKER_IP:7002
    - ECHO_BASEURL=$DOCKER_IP:8089
    - FRONT50_BASEURL=$DOCKER_IP:8080
    - OORT=$DOCKER_IP:8083
    - MORT_BASEURL=$DOCKER_IP:8083
    - IGOR_BASEURL=$DOCKER_IP:8088
    - ORCA_BASEURL=$DOCKER_IP:8083
  image: spinnaker/gate
  links: 
    - redis
  ports: 
    - "8084:8084"
  volumes: 
    - "../../config:/root/.spinnaker"
igor: 
  container_name: igor
  env_file: ./compose.env
  environment:
    - SERVICE_DEFAULT_HOST=$DOCKER_IP
    - ECHO_BASEURL=$DOCKER_IP:8089
  image: spinnaker/igor
  links: 
    - redis
  ports: 
    - "8088:8088"
  volumes: 
    - "../../config:/root/.spinnaker"
orca: 
  container_name: orca
  env_file: ./compose.env
  ports: 
    - "8083:8083"
  image: spinnaker/orca
  environment:
    - SERVICE_DEFAULT_HOST=$DOCKER_IP
  links: 
    - redis
  volumes: 
    - "../../config:/root/.spinnaker"
redis: 
  container_name: redis
  expose: 
    - "6379"
  image: redis